// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Thirdrun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Thirdrun));
        
        string IMigrationMetadata.Id
        {
            get { return "202210131838483_Thirdrun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
